# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-29 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='标题')),
                ('author', models.CharField(max_length=10, verbose_name='作者')),
                ('add_time', models.DateTimeField(verbose_name='添加时间')),
                ('body', models.TextField(max_length=500, verbose_name='文章')),
            ],
        ),
    ]
