# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-29 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Articles',
        ),
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
